Add readme with steps how to launch demo
y-crdt/ydotnet pull request #98
Opened 2024-05-18 05:46 UTC by andreyleskov

I tried to launch demo on local machine and stumbled upon many issues. 
As a person with backend C# background it took me three hours to launch the demo and see how yrdt persist documents 
in mongo. 
This is a great project and it deserves a better onboarding and demo launch experience. 
Please find the updated README.md with steps it took me to have demo up and running plus minor code changes.

2024-05-25 13:11 UTC, SebastianStehle commented
Sorry. I have forgotten to review your PR. I have only focused on the readme, because the other files also contain some test code. This needs to be cleaned up before something can be merged.

By default it should be possible to run the demo without MongoDB.

2024-06-04 00:33 UTC, andreyleskov commented
@SebastianStehle done, please review. Only left ReadMe, for launching with in-memory persistence locally with dependencies install.

This project is C# and I can imagine backend-heavy folks like me can be attracted for realtime collaboration feature, but struggle to launch it due to lack of knowledge with frontend part.
A good option in my opinion is to include a compose file and dockerfile with all the build and setup steps, to launch in one command.

2024-06-04 04:41 UTC, SebastianStehle requested changes

2024-06-04 04:41 UTC, SebastianStehle commented on Demo/README.md
> ++ Install .Net 7.0
You can use .Net 8.0 here, we just have not updated yet.

2024-07-08 11:28 UTC, SebastianStehle commented
Closing because of inactivity

2024-07-08 11:28 UTC, closed without merging